url: "https://btkbilecik.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Bilgisayar ve Teknoloji Kulübü" # the name of your site, e.g. ACME Corp.


collections:
  events:
    output: true
  roadmaps:
    output: true

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "roadmaps"
    values:
      layout: "roadmap"
      
# gelecek tarihli paylaşımları göster
future: true


plugins:
  - jekyll-seo-tag

social:
  name: btkbilecik
  links:
    - https://instagram.com/btkbilecik
    - https://linkedin.com/in/btkbilecik
    - https://github.com/btkbilecik